before_install:
  - git config --global user.email "sdamiano@stroudcenter.org"
  - git config --global user.name "SRGDamia1"

sudo: false
git:
  depth: 1
  sparse_checkout: travis/travis_sparse_checkout
branches:
  except:
    - gh-pages
cache:
  pip: true
  directories:
    - "~/.platformio"
    - $TRAVIS_BUILD_DIR/doxygen-src
language: python
python:
  - "2.7"
install:
  # Remove the cloned repo to emulate a user library installation
  - git rm library.json
  # - git rm library.properties
  # - git rm -r pioScripts
  # - git rm -r src
  # Install PlatformIO (this should be cached!)
  - pip install -U platformio
  - pio upgrade
  # Uninstall any old version of the current library from the Travis cache
  - if pio lib -g uninstall EnviroDIY_ModularSensors; then
    echo "Uninstalled cached version of ModularSensors";
    fi
  # Install this library from the branch we're working on
  # echo "Installing ModularSensors from https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_BRANCH";
  # echo "Installing ModularSensors from https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_BRANCH";
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Installing ModularSensors from https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_COMMIT";
    else
    echo "Installing ModularSensors from https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_SHA";
    fi
  # pio lib -g install https://github.com/$TRAVIS_REPO_SLUG.git#$BRANCH;
  # pio lib -g install https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_BRANCH;
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    pio lib -g install https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_COMMIT;
    else
    pio lib -g install https://github.com/$TRAVIS_PULL_REQUEST_SLUG.git#$TRAVIS_PULL_REQUEST_SHA;
    fi
  # Install serial libraries (these should be ignored by SAMD boards)
  - pio lib -g install https://github.com/PaulStoffregen/AltSoftSerial.git
  - pio lib -g install https://github.com/EnviroDIY/SoftwareSerial_ExtInts.git
  - pio lib -g install https://github.com/SRGDamia1/NeoSWSerial.git
  - pio update
script:
  - platformio ci --project-conf="travis/platformio.ini"

jobs:
  include:
    - name: "Verify library JSON format"
      language: node_js
      install: npm install -g jsonlint
      script: jsonlint -q library.json
      after_success: |
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
            curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
            sh trigger-travis.sh EnviroDIY Libraries $TRAVIS_ACCESS_TOKEN
        fi

    - name: "Build Doxygen Documentation"
      if: branch = master AND type != pull_request
      language: python
      python:
        - "3.7"
      before_install:
        - git config --global user.email "sdamiano@stroudcenter.org"
        - git config --global user.name "SRGDamia1"
        - git config --global push.default simple
        - sudo apt-get update
        - sudo apt-get -y install build-essential
        - sudo apt-get -y install graphviz
        - sudo apt-get -y install flex
        - sudo apt-get -y install bison
        - sudo apt-get -y install texlive-base
        - sudo apt-get -y install texlive-latex-extra
        - sudo apt-get -y install texlive-fonts-extra
        - sudo apt-get -y install texlive-fonts-recommended
        - pip3 install jinja2 Pygments
      install:
        - cd $TRAVIS_BUILD_DIR
        - chmod +x travis/copy-doc-sources.sh
        - sh travis/copy-doc-sources.sh
        - cd $TRAVIS_BUILD_DIR
        - chmod +x travis/build-install-doxygen.sh
        - sh travis/build-install-doxygen.sh
      script:
        - cd $TRAVIS_BUILD_DIR
        - chmod +x travis/generate-documentation.sh
        - sh travis/generate-documentation.sh
      # after_success:
      #   - cd $TRAVIS_BUILD_DIR
      #   - chmod +x travis/deploy-documentation.sh
      #   - sh travis/deploy-documentation.sh
      deploy:
        provider: pages:git
        token: $GH_REPO_TOKEN
        edge: true # opt in to dpl v2
        keep_history: false
        local_dir: $TRAVIS_BUILD_DIR/code_docs/ModularSensorsDoxygen/html
        project_name: ModularSensors

    - name: "Check Single Sensor Example"
      env:
        - PLATFORMIO_CI_SRC=examples/single_sensor/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check Simple Logging Example"
      env:
        - PLATFORMIO_CI_SRC=examples/simple_logging/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check DRWI CitSci 2G Example"
      env:
        - PLATFORMIO_CI_SRC=examples/DRWI_CitSci/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check DRWI CitSci LTE Example"
      env:
        - PLATFORMIO_CI_SRC=examples/DRWI_LTE/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check DRWI CitSci No Cellular Example"
      env:
        - PLATFORMIO_CI_SRC=examples/DRWI_NoCellular/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check Double Logger Example"
      env:
        - PLATFORMIO_CI_SRC=examples/double_logger/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check Baro Correction Example"
      env:
        - PLATFORMIO_CI_SRC=examples/baro_rho_correction/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check Data Saving Example"
      env:
        - PLATFORMIO_CI_SRC=examples/data_saving/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check ThingSpeak Example"
      env:
        - PLATFORMIO_CI_SRC=examples/logging_to_ThingSpeak/ PLATFORMIO_DEFAULT_ENVS="mayfly, adafruit_feather_m0, autonomo, mega"

    - name: "Check Menu Example"
      env:
        - PLATFORMIO_CI_SRC=examples/menu_a_la_carte/
